### ISSUE TITLE
[BUG] When installing the module, it isn't installed and throw an error 'unexpected token'

### ISSUE THREAD

**Issue by tameII** [ironmonk88/monks-combat-marker#13]
**Describe the bug**
When installing the module, it isn't installed and throw an error unexpected token

**To Reproduce**
1. Go to your Foundry app
2. Click on Modules (I have the app translated in French i hope it is the same words)
3. Click on "Install a module" (Pic 1)
4. Write `Monk's` in the search field
5. Click on *Installation" (Pic 2)
6. An error appear (Pic 3) `Unexpected token '<'` (detailed below)

**Expected behavior**
The module should be installed by clicking on "installation" without showing big red rectangle with sad text in it

**Screenshots**
Pic 1 - Button clicked to install a new module
![image](https://github.com/ironmonk88/monks-combat-marker/assets/26646585/d60d2177-642d-4521-b0e9-c3b040719c8d)

Pic 2 - Click on installation 
![image](https://github.com/ironmonk88/monks-combat-marker/assets/26646585/ab399889-3a76-4b6e-8850-403294a15cef)

Pic 3 - Error showed 
![image](https://github.com/ironmonk88/monks-combat-marker/assets/26646585/3a3c42e1-8fe7-4b5e-8665-a4ca5633339b)

**Please complete as much of the following information as possible:**
 - Browser : Firefox
 - Foundry Version 11 build 308
 - System  Pathfinder 2e 
 - Module version 11.03
 - Are there any errors in the console [e.g. press F12 and look for red text]
 ```
Uncaught (in promise) Error: Unable to load valid module manifest data from "https://github.com/ironmonk88/monks-combat-marker/releases/latest"
Error parsing module manifest data from https://github.com/ironmonk88/monks-combat-marker/releases/latest: Unexpected token '<', "






<!DOCTYPE "... is not valid JSON
 ```
 - No i have not tried using  `Find the Culprit` i don't understand what it is sorry

**Additional context**

I use FoundryVTT on a remote server, it's the first time for me doing that so i thought maybe it was the reason but the error does not seem to validate this thought.

List of the module installed 
![image](https://github.com/ironmonk88/monks-combat-marker/assets/26646585/bd8c7f99-c167-4de1-adf1-8a3340fc4dc7)

Thanks for reading me, have a nice day | night

**Comment by ironmonk108** [comment]
Try uninstalling and reinstalling.  
Foundry does weird things sometimes.

**Comment by rbak** [comment]
I'm seeing this same exact issue.  The module doesn't actually install.  The install button will say installed, but its not listed in the installed modules.  Closing the module-install window and re-opening changes the button back to "install" and I can try again, but get the same result every time.

Browser : Firefox (Also tried Edge and got the same result)
Foundry Version 11 build 313
Module version 11.03 (I tried to install every release tag for this repo by URL, and got the same error for every version)

I restarted the server and saw no change.  There's nothing else in the server logs to indicate a problem other than the "Unexpected token" message.

Also, I was able to install every other one of your modules that I tried without issue, so the problem does seem to be specific to this module.

**Comment by ericloyd** [comment]
Just tried installing for the first time on a newly installed 11.314 server and get the same error.

**Comment by ironmonk108** [comment]
Should be fixed now.
For the record... I really dislike Foundry's new webpage for updating packages.

**Comment by ericloyd** [comment]
Same.  I find it hard to see what I want to see when I look at the page now.

I can confirm that it now installs!  Thanks!!

**Comment by tameII** [comment]
I dislike it too because of this bug it told me it installed a lot of module without unziping it, causing them to not be recognized.

I confirm it installs correctly and the module work perfectly !

Thanks for the fast fix !
