### ISSUE TITLE
[REQUEST] Highlight start of turn square/hex to reference where a token was when it's turn started

### ISSUE THREAD

**Issue by LovelessLucidity** [ironmonk88/monks-combat-marker#9]
Big fan of your modules and have used them quite a lot over the last few years. One feature our particular group likes is knowing what square their token started on at the beginning of their turn in case of "Wait, where did I start? How far have I moved?". Keep up the good work! 

Currently running Foundry VTT v11.302 and Pathfinder 2e 5.0.2

**Comment by ironmonk108** [comment]
That's already covered in [Monk's Combat Details](https://foundryvtt.com/packages/monks-combat-details).
![image](https://github.com/ironmonk88/monks-combat-marker/assets/75920956/307e1539-9565-480d-b9fe-ade98f0ebee8)
![image](https://github.com/ironmonk88/monks-combat-marker/assets/75920956/5675dc6d-8be8-47f5-8f12-2acc7b859c07)

**Comment by LovelessLucidity** [comment]
Thanks for the response and apologies! I will get that installed.
